seqlist: seqlist.h seqlist.c main.c
	gcc -g $^ -o $@

seqlist_test: seqlist.h seqlist.c seqlist_test.c
	gcc -g $^ -o $@

linklist_test01: linklist.h linklist.c linklist_test01.c
	gcc -g $^ -o $@

seqstack_test01: seqstack.h seqstack.c seqstack_test01.c
	gcc -g $^ -o $@

clean:
	rm -f seqlist
